weights: /absolute/path/to/best.pt   # cập nhật tới best.pt sau fine-tune
imgsz: 640
device: auto          # auto|cuda|mps|cpu
conf_threshold: 0.25
classes: null         # ví dụ [0,1,2,3] để lọc; null = tất cả
use_tracking: true    # true: dùng model.track (có track_id)
names: ['Bus', 'Car', 'Motor', 'Truck']
