epochs: 50
batch: 16
imgsz: 640
device: 0            # 0 = GPU đầu; cpu = dùng CPU
workers: 8
patience: 20         # early stopping
optimizer: SGD       # SGD|Adam|AdamW
lr0: 0.01            # initial learning rate
lrf: 0.01            # final OneCycle LR ratio
weight_decay: 0.0005
momentum: 0.937
amp: true            # mixed precision
cache: false         # cache images to RAM
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.1
data: model_detection/data/dataset/data.yaml